### ISSUE TITLE
Hydrator construct Error 

### ISSUE THREAD

**Issue by ci83rtda** [didww/didww-api-3-php-sdk#21]
On my first attempt to use this package I get this error:
using master

Too few arguments to function Swis\JsonApi\Client\JsonApi\Hydrator::__construct(), 1 passed in /vendor/didww/didww-api-3-php-sdk/src/Configuration.php on line 35 and exactly 2 expected

Any idea?

**Comment by Fivell** [comment]
@ci83rtda  hello, I think this is error due wrong dependencies, can u check what version of 
didww-api-3-php-sdk and swisnl/json-api-client do u use?

it is possible that  https://github.com/didww/didww-api-3-php-sdk/pull/20 fixes your issue.  
so try to use latest didww-api-3-php-sdk  version 1.0.6

**Comment by ci83rtda** [comment]
Hello, you're right after setting didww-api-3-php-sdk to version 1.0.6 in my composer.json file fixed the issue.
thanks
