### ISSUE TITLE
LinkParser error

### ISSUE THREAD

**Issue by mobeelco** [didww/didww-api-3-php-sdk#22]
I got this error while trying to use the package with Laravel
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Swis\JsonApi\Client\JsonApi\LinksParser' not found

this my code
$credentials = new Credentials('xxxxxxxxxxxxxxxxx', 'production');

    Configuration::configure($credentials);

    $parameters = [
        'filter' => [
            'features' => 'sms',
            'available_dids_enabled'    =>  true,
            //  'needs_registration'    =>  false,
            'is_available'  =>  true,

        ],
        'include' => 'stock_keeping_units,country',
        'page'  =>  [
            'size'  =>  1000,
        ]
    ];
    $didGroupsDocument = \Didww\Item\DidGroup::all($parameters);
    $didGroups = $didGroupsDocument->getData();
    dd($didGroups);

**Comment by Fivell** [comment]
@mobeelco  try to freeze dependency 
swisnl/json-api-client to 0.17.0 ,  it was the last version that was tested with this package

**Comment by Fivell** [comment]
@mobeelco  or update to v1.0.7 , dependency was  freezed for this version
