### ISSUE TITLE
Argument 1 passed to Didww\Item\Did::setPendingRemoval() must be an instance of phpDocumentor\Reflection\Types\Boolean, boolean given

### ISSUE THREAD

**Issue by ci83rtda** [didww/didww-api-3-php-sdk#24]
Trying to renew using the following code

           `$did = new Did();
            $did->setId('did_id_string');
            $did->setPendingRemoval(false);
            $did->save();`

got: Argument 1 passed to Didww\Item\Did::setPendingRemoval() must be an instance of phpDocumentor\Reflection\Types\Boolean, boolean given.

Am I doing something wrong or how show I renew DID?

Asked here as well:
https://stackoverflow.com/questions/58703626/argument-1-passed-to-must-be-an-instance-of-boolean-given

**Comment by Fivell** [comment]
https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration

**Comment by Fivell** [comment]
@ci83rtda thanks for reporting , typo fixed, new version 🚀 https://github.com/didww/didww-api-3-php-sdk/releases/tag/v1.0.8
