### ISSUE TITLE
Get all country list is not working

### ISSUE THREAD

**Issue by sharif779** [didww/didww-api-3-php-sdk#26]
` $parameters = [
                'filter' => [
                    'prefix' => '1',
                ],
                'sort' => 'name', // -name for desceding order
            ];
$countriesDocument = \Didww\Item\Country::all($parameters);
`
Here I only get countries which prefix started 1.When I pass no parameter in function it raises error.
How can I get all the country lists.

**Comment by Fivell** [comment]
@sharif779  can you provide more details about error ?

**Comment by sharif779** [comment]
Thank you for replying.
Can you please tell me how can I get all the country lists.
And also available did list by filtering country code.
I follow your example https://github.com/didww/didww-api-3-php-sdk/blob/master/examples/orders_available_dids.php
But its not working.
Here is my code
`$credentials = new \Didww\Credentials('api_key', 'sandbox');
        \Didww\Configuration::configure($credentials, [
            'timeout' => 20,
            'debug' => true
            // 'sink' => STDOUT
        ]);
        $availableDidDocument = \Didww\Item\AvailableDid::find($country_uuid, ['include' => 'did_group.stock_keeping_units']);
        $didGroupRelation = $availableDidDocument->getData()->didGroup();
        log_me($didGroupRelation);`
But its return 
`Call to a member function didGroup() on null`

**Comment by gigorok** [comment]
@sharif779  you have requested invalid ID to the API. when you are uncomment `'sink' => STDOUT` you'll see that API returns 404

**Comment by Fivell** [comment]
@sharif779 please check if you use last version 1.0.8 
1) get all countries

```php
 $countriesDocument = \Didww\Item\Country::all();
 $countries = $countriesDocument->getData()->all();

 var_dump($countries);
```

2) filter DIDs  by countryID
```php
$availableDidsDocument = \Didww\Item\AvailableDid::all([
    'filter' => ['country.id' => $countryId],
    'include' => 'did_group.stock_keeping_units'
]);
$availableDids = $availableDidsDocument->getData()->all();

var_dump($availableDids);
```

**Comment by sharif779** [comment]
@Fivell  Yes get all countries worked.Thank you.
But filter DIDs by countryID not working .It shows following error
`Call to a member function all() on null`
@gigorok I uncomment `'sink' => STDOUT` but its dont return 404.It returns error that I mentioned.

**Comment by Fivell** [comment]
@sharif779  please show backtrace

**Comment by Fivell** [comment]
@sharif779  try to add such example and execute
```php
<?php
require_once 'bootstrap.php';

$countryId = '7eda11bb-0e66-4146-98e7-57a5281f56c8';


$availableDidsDocument = \Didww\Item\AvailableDid::all([
    'filter' => ['country.id' => $countryId],
    'include' => 'did_group.stock_keeping_units'
]);
$availableDids = $availableDidsDocument->getData()->all();

var_dump($availableDids[0]->getNumber());
```

I can see
```
string(12) "441213632104"
```

**Comment by Fivell** [comment]
@sharif779 seems you were using find instead of all while fetching available DIDs.
Closing this for now, feel free to comment if something goes wrong and I will reopen this ticket

**Comment by sharif779** [comment]
Ok Thank you for your helping @Fivell
