### ISSUE TITLE
\Didww\Item\Did does not return included CapacityPool() 

### ISSUE THREAD

**Issue by ooglek** [didww/didww-api-3-php-sdk#41]
I'm trying to get the CapacityPool() an active DID is assigned to.

However, when using the SDK, CapacityPool(), despite being included in the request, returns `null.`

**EXPECTED**

Using `$didlist[0]->capacityPool()->getIncluded()` returns a reference to a CapacityPool Item or list.

** ACTUAL **

Using `$didlist[0]->capacityPool()->getIncluded()` returns `null`

I'm using [psysh](https://psysh.org/) to load and run our code like a debugger.

PHP 7.3.5
DIDWW SDK v3.0.1

```
>>> $res = \Didww\Item\Did::all(['include' => 'did_group.stock_keeping_units,did_group.country,did_group.city,shared_capacity_group,capacity_pool','page'=>['number'=>1,'size'=>100]]);
=> Swis\JsonApi\Client\CollectionDocument {#9236}
>>> $didlist = $res->getData();
=> Swis\JsonApi\Client\Collection {#12337}
>>> $didlist->count()
=> 100
>>> $didlist[0]->getAttributes();
=> [
     "blocked" => false,
     "capacity_limit" => null,
     "description" => null,
     "terminated" => false,
     "awaiting_registration" => false,
     "created_at" => "2019-04-20T01:16:13.655Z",
     "billing_cycles_count" => null,
     "number" => "1201xxxxxxx",
     "expires_at" => "2022-02-20T01:16:13.813Z",
     "channels_included_count" => 0,
     "dedicated_channels_count" => 0,
   ]
>>> $didlist[0]->capacityPool()->getIncluded();
=> null
>>> $didlist[0]->getNumber()
=> "1201xxxxxxx"
>>> $didlist[0]->sharedCapacityGroup()->getIncluded()->getAttributes();
=> [
     "name" => "New Default",
     "shared_channels_count" => 0,
     "created_at" => "2018-08-27T10:12:46.347Z",
     "metered_channels_count" => 50,
   ]
```

**Comment by Fivell** [comment]
@ooglek , let me try to explain 
CapacityPool is storage with channels that can be used for shared channels for sharedCapacityGroups and dedicated channels for DID, 

relationships are next

1. DID optionally belongs to Capacity Pool  (indicates pool where channels are pulled or returned when you change dedicated_channels_count )
2. sharedCapacityGroup belongs to Capacity Pool (indicates pool where channels are pulled when you change shared_channels_count )
3. DID optionally belongs to sharedCapacityGroup and sharedCapacityGroup has many DIDs ( to use shared channels for many DIDs  )

also some DIDs can  already have channels_included_count that are bundled and can't be modified.

so 

Using $didlist[0]->capacityPool()->getIncluded() returns a reference to a CapacityPool Item or NULL.

Hope it helps.

**Comment by ooglek** [comment]
How do I determine if a DID is using Shared vs Metered Capacity Channels, and get the rate of that Metered Capacity Channel if the latter? This is my challenge. I want to programmatically determine my Metered Rates.

**Comment by Fivell** [comment]
@ooglek  
  \Didww\Item\Did::all(['include' => 'did_group.stock_keeping_units,did_group.country,did_group.city,shared_capacity_group.capacity_pool','page'=>['number'=>1,'size'=>100]]);
  here we including DID -> Capacity Group -> Capacity Pool 
  
  - Capacity Group has attributes metered_channels_count, shared_channels_count if both > 0 
   - Capacity pool has metered_rate, that applied of all calls performed using metered channels from this pool
 
 
 Also you can assign dedicated channels from pool , without capacity group (if you do not want to share this channels with other DIDs) 
 
 Example https://github.com/didww/didww-api-3-php-sdk/blob/81910186f93cff8b54ee358ad7e0dbfb321d1f63/examples/dids.php#L39
 
this way to fetch all the channels relations you can include both capacity pool of DID and shared capacity group. and its pool 

 ```
   \Didww\Item\Did::all(['include' => 'shared_capacity_group.capacity_pool,capacity_pool','page'=>['number'=>1,'size'=>100]]);
 
 ```
 
 Hope it makes sence for you
