### ISSUE TITLE
Guzzle 7 is not ok? Php 8.1 is not ok?

### ISSUE THREAD

**Issue by erimeilis** [didww/didww-api-3-php-sdk#52]
- didww/didww-api-3-php-sdk[v1.0.0, ..., v1.0.2] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.4.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - didww/didww-api-3-php-sdk[v1.0.3, ..., v1.0.8] require php ^7.1.3 -> your php version (8.1.9) does not satisfy that requirement.
    - Root composer.json requires didww/didww-api-3-php-sdk ^1.0 -> satisfiable by didww/didww-api-3-php-sdk[v1.0.0, ..., v1.0.8].

**Comment by gigorok** [comment]
@erimeilis Hello. Please try to use the latest v6.0.0 version
